# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rundiffTADs <- function(matlistcon1, matlistcon2, namecon1, namecon2, parnorm, parhierTADs, parFTRLreg) {
    .Call(`_TADfit_rundiffTADs`, matlistcon1, matlistcon2, namecon1, namecon2, parnorm, parhierTADs, parFTRLreg)
}

